import { Post } from "@/types";
import { addDocument } from "@/common/firebase";
import {
  polishCities,
  getCityInCase,
  PolishCase,
  generateCityContent,
} from "./polishCities";

// Generate a single city-based post
export function generateCityPost(citySlug: string): Post {
  const cityContent = generateCityContent(citySlug);
  const cityName = getCityInCase(citySlug, PolishCase.NOMINATIVE);
  const cityGenitive = getCityInCase(citySlug, PolishCase.GENITIVE);
  const cityLocative = getCityInCase(citySlug, PolishCase.LOCATIVE);

  if (!cityContent) {
    throw new Error(`No content available for city: ${citySlug}`);
  }

  const currentDate = Date.now();
  const postId = `tworzenie-stron-internetowych-${citySlug}-cennik`;
  const slug = `tworzenie-stron-internetowych-${citySlug}-cennik`;

  return {
    postId,
    title: `Tworzenie stron internetowych ${cityName} - Cennik`,
    metaTitle: `Tworzenie stron internetowych ${cityName} - Cennik`,
    metaDescription: `Profesjonalne ${cityContent.phrases.webDesignService.toLowerCase()}. Nowoczesne, responsywne strony WWW. Szybka realizacja, konkurencyjne ceny. Sprawdź naszą ofertę!`,
    metaKeywords: [
      `strona internetowa ${citySlug}`,
      `tworzenie stron ${citySlug}`,
      `projektowanie stron ${citySlug}`,
      `strony www ${citySlug}`,
      `web design ${citySlug}`,
      "quixy studio",
    ],
    intro: `Szukasz profesjonalnej strony internetowej ${cityContent.contexts.location}? Quixy Studio oferuje kompleksowe usługi tworzenia nowoczesnych, responsywnych stron WWW dostosowanych do potrzeb Twojej firmy.`,
    outro: `Skontaktuj się z nami już dziś i otrzymaj bezpłatną wycenę strony internetowej ${cityContent.contexts.location}. Nasze doświadczenie i pasja do web designu gwarantują najwyższą jakość usług.`,
    mainImage: "/assets/globe.jpg",
    images: ["/assets/globe.jpg"],
    creationTime: currentDate,
    readTime: 5,
    viewerCount: Math.floor(Math.random() * 500) + 100,
    tags: [
      "strona internetowa",
      "web design",
      "responsywność",
      citySlug,
      "quixy studio",
    ],
    url: slug,
    slug: slug,
    blogType: "city-landing",
    citySlug: citySlug,
    isAutogenerated: true,
    sections: [
      {
        title: `Dlaczego Warto Wybrać Nas ${cityContent.contexts.location}?`,
        content: `
          <p>Jako doświadczona agencja web designu, oferujemy:</p>
          <ul>
            <li><strong>Nowoczesny design</strong> - Tworzymy strony zgodne z najnowszymi trendami</li>
            <li><strong>Responsywność</strong> - Strony działają idealnie na wszystkich urządzeniach</li>
            <li><strong>Optymalizacja SEO</strong> - Pomagamy Ci być widocznym w Google</li>
            <li><strong>Szybkość działania</strong> - Optymalizujemy wydajność każdej strony</li>
            <li><strong>Lokalne wsparcie</strong> - ${cityContent.phrases.forResidents}</li>
          </ul>
        `,
        id: 1,
      },
      {
        title: "Nasze Usługi",
        content: `
          <h3>Kompleksowa oferta tworzenia stron internetowych:</h3>
          <p><strong>Strony wizytówkowe</strong> - Idealne dla małych firm i freelancerów</p>
          <p><strong>Strony firmowe</strong> - Profesjonalna prezentacja Twojej firmy online</p>
          <p><strong>Sklepy internetowe</strong> - Sprzedawaj online z nowoczesną platformą e-commerce</p>
          <p><strong>Blogi i portale</strong> - Dziel się treściami z łatwym w obsłudze CMS</p>
          <p><strong>Aplikacje webowe</strong> - Zaawansowane rozwiązania dla wymagających projektów</p>
        `,
        id: 2,
      },
      {
        title: "Proces Tworzenia Strony",
        content: `
          <ol>
            <li><strong>Konsultacja</strong> - Poznajemy Twoje potrzeby i cele biznesowe</li>
            <li><strong>Projektowanie</strong> - Tworzymy unikalny design dopasowany do Twojej marki</li>
            <li><strong>Programowanie</strong> - Kodujemy stronę z dbałością o każdy detal</li>
            <li><strong>Testowanie</strong> - Sprawdzamy działanie na wszystkich urządzeniach</li>
            <li><strong>Wdrożenie</strong> - Publikujemy stronę i przekazujemy Ci pełną kontrolę</li>
            <li><strong>Wsparcie</strong> - Zapewniamy ciągłe wsparcie techniczne</li>
          </ol>
        `,
        id: 3,
      },
      {
        title: `Lokalna Obsługa ${cityContent.contexts.location}`,
        content: `
          <p>${cityContent.phrases.localBusiness} specjalizująca się w tworzeniu profesjonalnych stron internetowych. ${cityContent.phrases.servingCity} od wielu lat, zapewniając:</p>
          <ul>
            <li><strong>Bezpośredni kontakt</strong> - Spotkania w biurze lub ${cityContent.contexts.location}</li>
            <li><strong>Lokalne referencje</strong> - Sprawdź opinie naszych klientów z ${cityGenitive}</li>
            <li><strong>Szybka reakcja</strong> - Wsparcie techniczne dostępne dla firm z ${cityGenitive}</li>
            <li><strong>Znajomość rynku</strong> - Rozumiemy specyfikę biznesu ${cityContent.contexts.location}</li>
          </ul>
          <p>Dołącz do grona zadowolonych klientów ${cityContent.contexts.location} i rozpocznij swoją cyfrową transformację już dziś!</p>
        `,
        id: 4,
      },
    ],
    faq: [
      {
        question: `Ile kosztuje strona internetowa ${cityContent.contexts.location}?`,
        answer: `Koszt strony internetowej zależy od jej złożoności i funkcjonalności. Podstawowa strona wizytówkowa zaczyna się od 2000 zł, podczas gdy sklep internetowy może kosztować od 5000 zł. ${cityContent.phrases.forResidents} oferujemy konkurencyjne ceny i możliwość płatności ratalnej.`,
      },
      {
        question: "Jak długo trwa tworzenie strony internetowej?",
        answer: `Typowa strona wizytówkowa jest gotowa w ciągu 2-3 tygodni. Bardziej złożone projekty, jak sklepy internetowe, mogą wymagać 4-8 tygodni. Dla klientów z ${cityGenitive} oferujemy szybkie terminy realizacji.`,
      },
      {
        question: "Czy zapewniacie hosting i domenę?",
        answer:
          "Tak, oferujemy kompleksowe usługi obejmujące hosting, domenę oraz SSL. Możemy również pomóc w konfiguracji hostingu u wybranego przez Ciebie dostawcy.",
      },
      {
        question: "Czy strona będzie responsywna?",
        answer:
          "Absolutnie! Wszystkie nasze strony są w 100% responsywne i działają idealnie na komputerach, tabletach i smartfonach. To standard w naszej pracy.",
      },
      {
        question: "Czy mogę sam edytować treści na stronie?",
        answer:
          "Tak, wszystkie nasze strony są wyposażone w łatwy w obsłudze panel administracyjny (CMS), który pozwala na samodzielną edycję treści, dodawanie zdjęć i zarządzanie stroną.",
      },
      {
        question: `Czy oferujecie wsparcie techniczne ${cityContent.contexts.location}?`,
        answer: `Tak! ${cityContent.phrases.forResidents} zapewniamy pełne wsparcie techniczne, w tym możliwość spotkań ${cityContent.contexts.location} oraz zdalną pomoc techniczną.`,
      },
    ],
  };
}

// Generate all city posts and save to database
export async function generateAndSaveAllCityPosts(): Promise<void> {
  console.log("Starting to generate city posts...");

  const results = {
    success: 0,
    errors: 0,
    total: polishCities.length,
  };

  for (const citySlug of polishCities) {
    try {
      const post = generateCityPost(citySlug);

      // Save to database
      await addDocument("blog", post.postId, post);

      results.success++;
      console.log(`✅ Generated post for ${citySlug}: ${post.title}`);

      // Add small delay to avoid overwhelming the database
      await new Promise((resolve) => setTimeout(resolve, 100));
    } catch (error) {
      results.errors++;
      console.error(`❌ Error generating post for ${citySlug}:`, error);
    }
  }

  console.log("\n=== Generation Summary ===");
  console.log(`Total cities: ${results.total}`);
  console.log(`Successful: ${results.success}`);
  console.log(`Errors: ${results.errors}`);
  console.log("City posts generation completed!");
}

// Check if city post exists in database
export async function cityPostExists(citySlug: string): Promise<boolean> {
  try {
    // This would need to be implemented based on your database query capabilities
    // For now, return false to always generate new posts
    return false;
  } catch (error) {
    console.error(`Error checking if city post exists for ${citySlug}:`, error);
    return false;
  }
}

// Generate a specific city post if it doesn't exist
export async function generateCityPostIfNeeded(
  citySlug: string
): Promise<Post | null> {
  try {
    const exists = await cityPostExists(citySlug);

    if (!exists) {
      const post = generateCityPost(citySlug);
      await addDocument("blog", post.postId, post);
      console.log(`Generated and saved post for ${citySlug}`);
      return post;
    }

    return null;
  } catch (error) {
    console.error(`Error generating city post for ${citySlug}:`, error);
    return null;
  }
}

// Update existing city posts with new content
export async function updateCityPost(citySlug: string): Promise<void> {
  try {
    const post = generateCityPost(citySlug);
    await addDocument("blog", post.postId, post);
    console.log(`Updated post for ${citySlug}`);
  } catch (error) {
    console.error(`Error updating city post for ${citySlug}:`, error);
  }
}
