export const mapMarkers = [
  {
    id: "szczecin",
    top: "40%",
    left: "9.5%",
    leftSm: "8.5%",
    width: "8%",
    text: "Szczecin - Strona internetowa dla restauracji",
  },
  {
    id: "zielona-gora",
    top: "58%",
    left: "18%",
    width: "10%",
    text: "Zielona Góra - Sklep online z elektroniką",
  },
  {
    id: "wroclaw",
    top: "69%",
    left: "33%",
    width: "6%",
    text: "Wrocław - Portfolio fotografa",
  },
  {
    id: "opole",
    top: "76%",
    left: "43%",
    width: "6%",
    text: "Opole - Strona dla kancelarii prawnej",
  },
  {
    id: "katowice",
    top: "67%",
    left: "44.5%",
    width: "6%",
    text: "Katowice - Sklep internetowy z odzieżą",
  },
  {
    id: "krakow",
    top: "81%",
    left: "56.5%",
    width: "8%",
    text: "Kraków - Strona internetowa dla hotelu",
  },
  {
    id: "rzeszow",
    top: "78%",
    left: "72.5%",
    width: "8%",
    text: "Rzeszów - Portal edukacyjny",
  },
  {
    id: "lublin",
    top: "57%",
    left: "79%",
    width: "10%",
    text: "Lublin - Strona internetowa dla lekarza",
  },
];
